#!/usr/bin/env node
// CSS assembler (TDD CSS delivery, "Compile and assemble" steps 1-6). Writes
// the one aggregate component stylesheet, @scnx/system/styles/components.css:
//   1. Sass compiles src/styles/bundles/components.scss into the reset, base,
//      and components layers;
//   2. Panda's frozen recipes are appended in the recipes layer. Panda's own
//      reset, base, tokens, and utilities output is not published: it targets
//      :root and markup outside a theme root;
//   3. the stylesheet gate checks every published stylesheet.
// Component JavaScript imports no CSS; the stylesheet is packed on its own.
//
//   node scripts/styles/assemble.mjs --out <dist dir>

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as csstree from "css-tree";
import * as sass from "sass";
import { checkDist } from "./check-css.mjs";

const packageDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const HEADER = "/* Generated by @scnx/system scripts/styles/assemble.mjs. Do not edit. */";

/** Every component stylesheet must be loaded by the bundle (Failure Handling: missing CSS). */
function assertBundleComplete(bundleFile) {
  const bundle = fs.readFileSync(bundleFile, "utf8");
  const missing = [];
  const visit = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) visit(full);
      else if (entry.name.endsWith(".scss")) {
        const module = path.relative(path.join(packageDir, "src"), full).replaceAll("\\", "/").replace(/\.scss$/, "");
        if (!bundle.includes(`meta.load-css("${module}")`)) missing.push(module);
      }
    }
  };
  visit(path.join(packageDir, "src/components"));
  if (missing.length > 0) throw new Error(`components.scss does not load: ${missing.join(", ")}`);
}

/**
 * The rules of Panda's `recipes` layer, with its internal `_base` sublayer
 * flattened ahead of the variant rules. Within the layer, base and variant
 * selectors have equal specificity, so source order keeps base below variants.
 */
export function pandaRecipes(css) {
  const ast = csstree.parse(css, { positions: true });
  const text = (node) => css.slice(node.loc.start.offset, node.loc.end.offset);
  const layer = ast.children.toArray().find(
    (node) => node.type === "Atrule" && node.name === "layer" && node.block && csstree.generate(node.prelude) === "recipes",
  );
  if (!layer) throw new Error("Panda emitted no recipes layer");
  const base = [];
  const variants = [];
  for (const node of layer.block.children.toArray()) {
    if (node.type === "Atrule" && node.name === "layer") {
      const name = csstree.generate(node.prelude);
      if (name !== "_base") throw new Error(`unexpected Panda sublayer "${name}" in recipes`);
      base.push(...node.block.children.toArray().map(text));
    } else {
      variants.push(text(node));
    }
  }
  return [...base, ...variants].map((rule) => `  ${rule.trim()}`).join("\n\n");
}

function runPanda() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "scnx-panda-"));
  const outfile = path.join(dir, "panda.css");
  try {
    execFileSync(path.join(packageDir, "node_modules/.bin/panda"), ["cssgen", "--outfile", outfile], {
      cwd: packageDir,
      stdio: ["ignore", "ignore", "inherit"],
    });
    return fs.readFileSync(outfile, "utf8");
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

export function assemble(outDir) {
  const bundle = path.join(packageDir, "src/styles/bundles/components.scss");
  assertBundleComplete(bundle);
  const compiled = sass.compile(bundle, {
    loadPaths: [path.join(packageDir, "src")],
    charset: false,
    style: "expanded",
  }).css;
  const css = `${HEADER}\n${compiled}\n\n@layer recipes {\n${pandaRecipes(runPanda())}\n}\n`;
  const target = path.join(outDir, "styles/components.css");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, css);
  return checkDist(outDir);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const index = process.argv.indexOf("--out");
  try {
    const report = assemble(path.resolve(index > -1 ? process.argv[index + 1] : "dist"));
    for (const [sheet, { rules, declarations }] of Object.entries(report)) {
      const layers = Object.entries(rules).filter(([, n]) => n > 0).map(([l, n]) => `${l}:${n}`).join(" ");
      console.log(`${sheet.padEnd(28)} ${String(declarations).padStart(5)} declarations  ${layers}`);
    }
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}
