#!/usr/bin/env node
// Emitters (TDD tokens, "Normalize and resolve" step 8; API / Interface):
// serialize one normalized record set into
//   tokens/css/<theme-id>.css   scoped custom properties per declared mode
//   tokens/json/<theme-id>.json typed records per mode
//   tokens/scss/_index.scss     Sass variables that reference the properties
//   fonts/*                     declared font faces and licenses
// Output is sorted and free of timestamps, so the same source emits the same
// bytes. Emission stops if theme key sets differ or a value cannot be
// serialized (TDD tokens, Failure Handling).
//
//   node scripts/tokens/emit.mjs --out <dir>

import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadConfig } from "./check.mjs";
import { STANDARD, parseTokenName, tokenType } from "./grammar.mjs";
import { normalize } from "./normalize.mjs";
import { assertDeclarationSafe, toCss } from "./serialize.mjs";
import { fontFamilies, keySetFindings, substitute } from "./validate.mjs";

const HEADER = "Generated by @scnx/system scripts/tokens/emit.mjs from the token source. Do not edit.";

/** Selector of one theme/mode root (TDD tokens, API / Interface). */
export function themeSelector(themeId, mode) {
  return `[data-scnx-theme="${themeId}"][data-scnx-resolved-mode="${mode}"]`;
}

/** Serialize every record of every theme/mode, or throw with all failures. */
export function serializeThemes(themes, aliases = {}) {
  const failures = keySetFindings(themes, aliases).map((f) => `${f.theme}/${f.mode} ${f.token}: ${f.message}`);
  const out = {};
  for (const [themeId, modes] of Object.entries(themes)) {
    out[themeId] = {};
    for (const [mode, { records }] of Object.entries(modes)) {
      const values = new Map();
      for (const name of [...records.keys()].sort()) {
        try {
          const css = toCss(records.get(name));
          assertDeclarationSafe(css);
          values.set(name, css);
        } catch (error) {
          failures.push(`${themeId}/${mode} ${name}: ${error.message}`);
        }
      }
      out[themeId][mode] = values;
    }
  }
  if (failures.length > 0) throw new Error(`Token emission stopped:\n${failures.join("\n")}`);
  return out;
}

function fontFaces(families, config, cssDir) {
  const rules = [];
  for (const family of families) {
    const asset = config.fonts.assets[family];
    if (!asset) continue;
    for (const face of asset.faces) {
      const url = path.posix.relative(cssDir, face.publish);
      rules.push(
        `@font-face {\n  font-family: "${family}";\n  font-style: ${face.style};\n  font-weight: ${face.weight};\n  font-display: swap;\n  src: url("${url}") format("woff2");\n}`,
      );
    }
  }
  return rules;
}

/** CSS for one theme: font faces it uses, then one scoped block per mode. */
export function themeCss(themeId, modes, config) {
  const cssDir = "tokens/css";
  const families = new Set();
  const blocks = [];
  for (const [mode, values] of Object.entries(modes)) {
    const lookup = (name) => values.get(name);
    for (const [name, css] of values) {
      if (tokenType(name, config.aliases) === "fontFamily") {
        for (const family of fontFamilies(substitute(css, lookup).value)) families.add(family);
      }
    }
    const declarations = [...values].map(([name, css]) => `  ${name}: ${css};`).join("\n");
    blocks.push(`${themeSelector(themeId, mode)} {\n${declarations}\n}`);
  }
  return [`/* ${HEADER} */`, ...fontFaces([...families].sort(), config, cssDir), ...blocks].join("\n\n") + "\n";
}

/** Typed records for one theme (TDD tokens, Data Model: TokenRecord). */
export function themeJson(themeId, modes, config) {
  const aliases = config.aliases ?? {};
  const names = [...new Set(Object.values(modes).flatMap((values) => [...values.keys()]))].sort();
  const tokens = names.map((cssName) => {
    const parsed = parseTokenName(cssName, aliases);
    const record = {
      name: parsed.valid ? parsed.path : cssName.slice("--ds-".length).replaceAll("-", "."),
      cssName,
      canonical: parsed.valid,
      tier: parsed.valid ? parsed.tier : null,
      type: tokenType(cssName, aliases),
      lifecycle: "candidate",
      themes: { [themeId]: {} },
      resolved: { [themeId]: {} },
    };
    for (const [mode, values] of Object.entries(modes)) {
      const css = values.get(cssName);
      record.themes[themeId][mode] = css;
      record.resolved[themeId][mode] = substitute(css, (name) => values.get(name)).value;
      const single = /^var\((--ds-[\w-]+)\)$/.exec(css);
      if (single) record.reference = single[1];
    }
    return record;
  });
  return `${JSON.stringify({ schemaVersion: 1, standard: STANDARD, theme: themeId, modes: Object.keys(modes), tokens }, null, 2)}\n`;
}

/** Sass contract: one variable per token, a name map, and a checked lookup. */
export function sassIndex(names) {
  const sorted = [...names].sort();
  const variable = (name) => name.slice("--ds-".length);
  return [
    `// ${HEADER}`,
    "// Each variable references the custom property, so values follow the",
    "// theme and mode selected on the nearest scoped root.",
    '@use "sass:map";',
    "",
    ...sorted.map((name) => `$${variable(name)}: var(${name});`),
    "",
    "$tokens: (",
    ...sorted.map((name) => `  "${variable(name)}": var(${name}),`),
    ");",
    "",
    "/// The custom property reference of a token, by name without --ds-.",
    "@function token($name) {",
    "  @if not map.has-key($tokens, $name) {",
    '    @error "Unknown token \\"#{$name}\\".";',
    "  }",
    "  @return map.get($tokens, $name);",
    "}",
    "",
  ].join("\n");
}

/** Emit every artifact into `outDir`; returns [{ file, sha256, bytes }]. */
export function emit({ packageDir, outDir }) {
  const config = loadConfig(path.join(packageDir, "tokens.config.json"));
  const { themes } = normalize({ packageDir, config });
  const serialized = serializeThemes(themes, config.aliases);
  const files = [];
  const write = (relative, content) => {
    const target = path.join(outDir, relative);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content);
    files.push({ file: relative, sha256: createHash("sha256").update(content).digest("hex"), bytes: Buffer.byteLength(content) });
  };

  const names = new Set();
  for (const [themeId, modes] of Object.entries(serialized)) {
    for (const values of Object.values(modes)) for (const name of values.keys()) names.add(name);
    write(`tokens/css/${themeId}.css`, themeCss(themeId, modes, config));
    write(`tokens/json/${themeId}.json`, themeJson(themeId, modes, config));
  }
  write("tokens/scss/_index.scss", sassIndex(names));

  for (const asset of Object.values(config.fonts.assets)) {
    for (const file of [...asset.faces, asset.license]) {
      write(file.publish, fs.readFileSync(path.join(packageDir, file.source)));
    }
  }
  return files;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const index = process.argv.indexOf("--out");
  if (index === -1) {
    console.error("usage: emit.mjs --out <dir>");
    process.exit(1);
  }
  const packageDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
  try {
    const files = emit({ packageDir, outDir: path.resolve(process.argv[index + 1]) });
    for (const { file, bytes, sha256 } of files) console.log(`${file.padEnd(40)} ${String(bytes).padStart(8)} B  ${sha256.slice(0, 16)}`);
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}
